# Generated by Django 2.2.6 on 2019-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_id',
            field=models.IntegerField(default=0),
        ),
    ]
