# Generated by Django 2.2.6 on 2019-10-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_auto_20191029_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='has_data',
            field=models.BooleanField(default=False),
        ),
    ]
